name = "discord-bot"
main = "./src/bot.js"
compatibility_date="2024-12-25"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID

[triggers]
crons = [ "*/3 * * * *" ]

[[d1_databases]]
binding = "DB"
database_name = "discord_data"
database_id = "your-database-id"